name: hpc-sim
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ansi2html=1.8.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cryptography=41.0.7
  - dash=2.14.2
  - flask=2.2.2
  - flask-compress=1.13
  - idna=3.4
  - importlib-metadata=6.0.0
  - intel-openmp=2023.1.0
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numexpr=2.8.7
  - numpy=1.26.2
  - numpy-base=1.26.2
  - openssl=3.0.12
  - pandas=2.1.4
  - pip=23.3.1
  - plotly=5.9.0
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - readline=8.2
  - requests=2.31.0
  - retrying=1.3.3
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tenacity=8.2.2
  - tk=8.6.12
  - typing_extensions=4.7.1
  - tzdata=2023c
  - urllib3=1.26.18
  - werkzeug=2.2.3
  - wheel=0.41.2
  - xz=5.4.5
  - zipp=3.11.0
  - zlib=1.2.13
  - pip:
    - dash-bootstrap-components==1.5.0
    - dnspython==2.4.2
    - pymongo==4.6.1
    - jsonpickle==3.0.3
    - kaleido==0.2.1
