name: "Example"
workloads:
  # The nancy workload(s)
  - &default_workload
    db: "mongodb+srv://cslab:bQt5TU6zQsu_LZ@storehouse.om2d9c0.mongodb.net"
    loads-machine: "remake-g5k.nancy.grvingt"
    loads-suite: "NAS"
    generator:
      type: "Random Generator"
      arg: 1000
    cluster:
      nodes: 8
      socket-conf: [16, 16]
    repeat: 1
  # The aris workload(s)
  - <<: *default_workload
    loads-machine: "aris.compute"
    generator:
      type: "Random Generator"
      arg: 200
    cluster:
      nodes: 420
      socket-conf: [10, 10]
schedulers:
  default: "FIFO Scheduler"
  others:
    - "EASY Scheduler"
    - "Conservative Scheduler"
    - "Random Ranks Co-Scheduler"
    - "/home/stratos/Development/Job/HPC-Simulator/framework/realsim/scheduler/coschedulers/ranks/filler.py"
  general-options:
    backfill_enabled: true
    compact_fallback: true
actions:
  get_gantt_representation:
    workloads: "all"
    schedulers: "all"
    img_dir: "./images"
  get_workload:
    workloads: "all"
    schedulers: "all"
    workload_dir: "./csvs"
...
